### ISSUE TITLE
Quilt 1.20.1 crash

### ISSUE THREAD

**Issue by alinka62679** [PssbleTrngle/SliceAndDice#139]
### What happened?

The game does not start, the version QKL 3.0.0 + FLK 1.10.17 + Kotlin 1.9.22

### Loader

forge

### Mod Version

3.1.0

### Minecraft Version

1.20

### Crash report

[crash-2024-03-27_11.18.18-client.txt](https://github.com/PssbleTrngle/SliceAndDice/files/14770311/crash-2024-03-27_11.18.18-client.txt)

### Relevant log output

```Shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-03-27 11:18:18
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'sliceanddice'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoSuchFieldError: BASE_CREATIVE_TAB
	at com.possible_triangle.sliceanddice.Content.<clinit>(Content.kt:69)
	at com.possible_triangle.sliceanddice.SliceAndDice.onInitialize(SliceAndDice.java:17)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 12 more
```

**Comment by PssbleTrngle** [comment]
Which version of create are you using?

**Comment by alinka62679** [comment]
https://modrinth.com/mod/create-fabric-dme-edition
[Create 1.20.1 v0.5.1.d Patch 4]

**Comment by PssbleTrngle** [comment]
Sorry, only the official create fabric port of supported
