### ISSUE TITLE
NPE Crash on Fabric on joining a world with sprinkler

### ISSUE THREAD

**Issue by Partonetrain** [PssbleTrngle/SliceAndDice#145]
### What happened?

Tried to join a world that has an active sprinkler, and game crashed.

### Loader

fabric

### Mod Version

3.2.1

### Minecraft Version

1.20

### Relevant log output

```Shell
java.lang.NullPointerException: Cannot load from object array because the return value of "net.fabricmc.fabric.api.transfer.v1.client.fluid.FluidVariantRenderHandler.getSprites(net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant)" is null
	at com.simibubi.create.content.fluids.particle.FluidStackParticle.<init>(FluidStackParticle.java:38)
	at com.simibubi.create.content.fluids.particle.FluidStackParticle.create(FluidStackParticle.java:28)
	at com.simibubi.create.content.fluids.particle.FluidParticleData.create(FluidParticleData.java:46)
	at net.minecraft.class_702.method_3055(class_702.java:348)
	at net.minecraft.class_702.method_3056(class_702.java:333)
	at net.minecraft.class_761.method_3288(class_761.java:2759)
	at net.minecraft.class_761.method_8563(class_761.java:2719)
	at net.minecraft.class_761.method_8568(class_761.java:2714)
	at net.minecraft.class_638.method_8406(class_638.java:600)
	at com.possible_triangle.sliceanddice.block.sprinkler.SprinklerTile.spawnProcessingParticles(SprinklerTile.kt:81)
	at com.possible_triangle.sliceanddice.block.sprinkler.SprinklerTile.tick(SprinklerTile.kt:65)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_638.method_18116(class_638.java:259)
	at net.minecraft.class_310.method_1574(class_310.java:1901)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Steve-651** [comment]
Same.

I'm also on Fabric 1.20.1, mod version 3.2.1.

Here's the extended stacktrace: 

`
net.minecraft.class_148: Exception while adding particle
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:676) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:470) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:259) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1901) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
Caused by: java.lang.NullPointerException: Cannot load from object array because the return value of "net.fabricmc.fabric.api.transfer.v1.client.fluid.FluidVariantRenderHandler.getSprites(net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant)" is null
	at com.simibubi.create.content.fluids.particle.FluidStackParticle.<init>(FluidStackParticle.java:38) ~[create-fabric-0.5.1-f-build.1335+mc1.20.1.jar:?]
	at com.simibubi.create.content.fluids.particle.FluidStackParticle.create(FluidStackParticle.java:28) ~[create-fabric-0.5.1-f-build.1335+mc1.20.1.jar:?]
	at com.simibubi.create.content.fluids.particle.FluidParticleData.create(FluidParticleData.java:46) ~[create-fabric-0.5.1-f-build.1335+mc1.20.1.jar:?]
	at net.minecraft.class_702.method_3055(class_702.java:348) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_3056(class_702.java:333) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3288(class_761.java:2759) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8563(class_761.java:2719) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8568(class_761.java:2714) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_8406(class_638.java:600) ~[client-intermediary.jar:?]
	at com.possible_triangle.sliceanddice.block.sprinkler.SprinklerTile.spawnProcessingParticles(SprinklerTile.kt:81) ~[sliceanddice-fabric-3.2.1.jar:?]
	at com.possible_triangle.sliceanddice.block.sprinkler.SprinklerTile.tick(SprinklerTile.kt:65) ~[sliceanddice-fabric-3.2.1.jar:?]
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15) ~[create-fabric-0.5.1-f-build.1335+mc1.20.1.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) ~[client-intermediary.jar:?]
`
