### ISSUE TITLE
Parameter specified as non-null is null: side

### ISSUE THREAD

**Issue by CassieRoseZA** [PssbleTrngle/SliceAndDice#148]
### What happened?

When looking at the slicer with WTHIT it prints this error in chat
Error on retrieving data from provider mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider$$Lambda$39640/0x0000000804092af0

### Loader

fabric

### Mod Version

3.2.1

### Minecraft Version

1.20

### Relevant log output

```Shell
b[15:20:58] [Server thread/ERROR]: [WTHIT] Caught unhandled exception : [class mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider$$Lambda$39640/0x0000000804092af0
player CassieRoseZA] java.lang.NullPointerException: Parameter specified as non-null is null: method com.possible_triangle.sliceanddice.block.slicer.SlicerTile.getItemStorage, parameter side
[15:20:58] [Server thread/ERROR]: [WTHIT] java.lang.NullPointerException: Parameter specified as non-null is null: method com.possible_triangle.sliceanddice.block.slicer.SlicerTile.getItemStorage, parameter side
	at com.possible_triangle.sliceanddice.block.slicer.SlicerTile.getItemStorage(SlicerTile.kt)
	at net.fabricmc.fabric.api.transfer.v1.item.ItemStorage.lambda$static$1(ItemStorage.java:98)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiCacheImpl.find(BlockApiCacheImpl.java:95)
	at mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider.lambda$appendData$0(ItemStorageProvider.java:39)
	at mcp.mobius.waila.access.DataWriter.lambda$send$1(DataWriter.java:81)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at mcp.mobius.waila.access.DataWriter.send(DataWriter.java:75)
	at mcp.mobius.waila.network.Packets.lambda$initServer$10(Packets.java:166)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by PssbleTrngle** [comment]
Should be fixed in the latest release
