### ISSUE TITLE
Crash loading in 1.19.2

### ISSUE THREAD

**Issue by brianfreud** [PssbleTrngle/SliceAndDice#34]
### What happened?

Using 1.19.2 with v2.0.0, Forge v43.2.0, I get a null invocation crash from this mod.  From debug.log:

[18Feb2023 21:44:09.979] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: sliceanddice, class com.possible_triangle.sliceanddice.SliceAndDice
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23394!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23393!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at com.possible_triangle.sliceanddice.Content.createRecipeType(Content.kt:95) ~[sliceanddice-2.0.0.jar%23361!/:2.0.0]
	at com.possible_triangle.sliceanddice.Content.<clinit>(Content.kt:98) ~[sliceanddice-2.0.0.jar%23361!/:2.0.0]
	at com.possible_triangle.sliceanddice.SliceAndDice.<init>(SliceAndDice.java:16) ~[sliceanddice-2.0.0.jar%23361!/:2.0.0]
	... 14 more
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.possible_triangle.sliceanddice.Content.createRecipeType(Content.kt:95) ~[sliceanddice-2.0.0.jar%23361!/:2.0.0]
	at com.possible_triangle.sliceanddice.Content.<clinit>(Content.kt:98) ~[sliceanddice-2.0.0.jar%23361!/:2.0.0]
	at com.possible_triangle.sliceanddice.SliceAndDice.<init>(SliceAndDice.java:16) ~[sliceanddice-2.0.0.jar%23361!/:2.0.0]
	... 14 more

### Mod Version

2.0.0

### Minecraft Version

None

### Forge Version

43.2.0

**Comment by PssbleTrngle** [comment]
You're missing "Kotlin for Forge"
