### ISSUE TITLE
v2.0.1 client crash

### ISSUE THREAD

**Issue by N0BEH** [PssbleTrngle/SliceAndDice#37]
### What happened?

Updated your mod version from 2.0.0 to 2.0.1 in my modded server and the slicer cause crash for every player who had alreay a slicer in its base. Of course i have updated kotklin for forge.

I downgraded to 2.0.0 slice and dice and the crash issues is gone.

### Mod Version

2.0.1

### Minecraft Version

None

### Forge Version

43.2.3

### Relevant log output

```shell
Time: 2023-02-22 08:57:09
Description: Unexpected error

java.lang.ExceptionInInitializerError: null
	at com.possible_triangle.sliceanddice.block.slicer.SlicerInstance.<init>(SlicerInstance.kt:21) ~[sliceanddice-2.0.1.jar%23367!/:2.0.1] {re:classloading}
	at com.possible_triangle.sliceanddice.Content.SLICER_TILE$lambda-5$lambda-4(Content.kt:82) ~[sliceanddice-2.0.1.jar%23367!/:2.0.1] {re:mixin,re:classloading}
	at com.jozufozu.flywheel.backend.instancing.blockentity.SimpleBlockEntityInstancingController.createInstance(SimpleBlockEntityInstancingController.java:21) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderRegistry.createInstance(InstancedRenderRegistry.java:62) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading,re:mixin}
	at com.jozufozu.flywheel.backend.instancing.blockentity.BlockEntityInstanceManager.createRaw(BlockEntityInstanceManager.java:27) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.blockentity.BlockEntityInstanceManager.createRaw(BlockEntityInstanceManager.java:14) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.createInternal(InstanceManager.java:328) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.addInternal(InstanceManager.java:313) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.processQueuedAdditions(InstanceManager.java:290) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.beginFrame(InstanceManager.java:147) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.beginFrame(InstanceWorld.java:96) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.onBeginFrame(InstancedRenderDispatcher.java:95) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at com.jozufozu.flywheel.backend.instancing.__InstancedRenderDispatcher_onBeginFrame_BeginFrameEvent.invoke(.dynamic) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$bdj000$setupRender(LevelRenderer.java:17122) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1158) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: PartialModel 'sliceanddice:block/slicer/head' loaded after ModelEvent.RegisterAdditional
	at com.jozufozu.flywheel.core.PartialModel.<init>(PartialModel.java:31) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.possible_triangle.sliceanddice.SlicerPartials.<clinit>(SlicerPartials.kt:7) ~[sliceanddice-2.0.1.jar%23367!/:2.0.1] {re:classloading}
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.possible_triangle.sliceanddice.block.slicer.SlicerInstance.<init>(SlicerInstance.kt:21) ~[sliceanddice-2.0.1.jar%23367!/:2.0.1] {re:classloading}
	at com.possible_triangle.sliceanddice.Content.SLICER_TILE$lambda-5$lambda-4(Content.kt:82) ~[sliceanddice-2.0.1.jar%23367!/:2.0.1] {re:mixin,re:classloading}
	at com.jozufozu.flywheel.backend.instancing.blockentity.SimpleBlockEntityInstancingController.createInstance(SimpleBlockEntityInstancingController.java:21) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderRegistry.createInstance(InstancedRenderRegistry.java:62) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading,re:mixin}
	at com.jozufozu.flywheel.backend.instancing.blockentity.BlockEntityInstanceManager.createRaw(BlockEntityInstanceManager.java:27) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.blockentity.BlockEntityInstanceManager.createRaw(BlockEntityInstanceManager.java:14) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.createInternal(InstanceManager.java:328) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.addInternal(InstanceManager.java:313) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.processQueuedAdditions(InstanceManager.java:290) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.beginFrame(InstanceManager.java:147) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.beginFrame(InstanceWorld.java:96) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.onBeginFrame(InstancedRenderDispatcher.java:95) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at com.jozufozu.flywheel.backend.instancing.__InstancedRenderDispatcher_onBeginFrame_BeginFrameEvent.invoke(.dynamic) ~[flywheel-forge-1.19.2-0.6.8.a-14.jar%23419!/:0.6.8.a-14] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$bdj000$setupRender(LevelRenderer.java:17122) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1158) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['NOBEH'/76162, l='ClientLevel', x=17660.50, y=68.10, z=13162.50]]
	Chunk stats: 4096, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 58755458 game time, 878019 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23391!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by PssbleTrngle** [comment]
Should be fixed now
