### ISSUE TITLE
Mod crashes on servers with latest create forge update

### ISSUE THREAD

**Issue by ModernGamingWorld** [PssbleTrngle/SliceAndDice#85]
### What happened?

[24.06 20:29:55] [Server] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: sliceanddice, class com.possible_triangle.sliceanddice.SliceAndDice
[24.06 20:29:55] [Server] java.lang.reflect.InvocationTargetExceptionnull
[24.06 20:29:55] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[24.06 20:29:55] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[24.06 20:29:55] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[24.06 20:29:55] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[24.06 20:29:55] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[24.06 20:29:55] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.14.jar%23951!/:?] {}
[24.06 20:29:55] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.14.jar%23950!/:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:mixin,re:computing_frames}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:mixin,re:computing_frames}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {re:mixin}
[24.06 20:29:55] [Server] Caused byjava.lang.NoClassDefFoundError: com/simibubi/create/content/AllSections
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.Content$REGISTRATE.<clinit>(Content.kt:62) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:classloading}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.Content.<clinit>(Content.kt:80) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:mixin,re:classloading}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.SliceAndDice.<init>(SliceAndDice.java:16) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:classloading}
[24.06 20:29:55] [Server] 	... more
[24.06 20:29:55] [Server] Caused byjava.lang.ClassNotFoundException: com.simibubi.create.content.AllSections
[24.06 20:29:55] [Server] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
[24.06 20:29:55] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[24.06 20:29:55] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
[24.06 20:29:55] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[24.06 20:29:55] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
[24.06 20:29:55] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.Content$REGISTRATE.<clinit>(Content.kt:62) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:classloading}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.Content.<clinit>(Content.kt:80) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:mixin,re:classloading}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.SliceAndDice.<init>(SliceAndDice.java:16) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:classloading}
[24.06 20:29:55] [Server] 	... more

### Loader

forge

### Mod Version

Latest version

### Minecraft Version

1.19

### Relevant log output

```shell
[24.06 20:29:55] [Server] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: sliceanddice, class com.possible_triangle.sliceanddice.SliceAndDice
[24.06 20:29:55] [Server] java.lang.reflect.InvocationTargetExceptionnull
[24.06 20:29:55] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[24.06 20:29:55] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[24.06 20:29:55] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[24.06 20:29:55] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[24.06 20:29:55] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[24.06 20:29:55] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.14.jar%23951!/:?] {}
[24.06 20:29:55] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.14.jar%23950!/:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:mixin,re:computing_frames}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:mixin,re:computing_frames}
[24.06 20:29:55] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {re:mixin}
[24.06 20:29:55] [Server] Caused byjava.lang.NoClassDefFoundError: com/simibubi/create/content/AllSections
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.Content$REGISTRATE.<clinit>(Content.kt:62) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:classloading}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.Content.<clinit>(Content.kt:80) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:mixin,re:classloading}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.SliceAndDice.<init>(SliceAndDice.java:16) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:classloading}
[24.06 20:29:55] [Server] 	... more
[24.06 20:29:55] [Server] Caused byjava.lang.ClassNotFoundException: com.simibubi.create.content.AllSections
[24.06 20:29:55] [Server] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
[24.06 20:29:55] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[24.06 20:29:55] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
[24.06 20:29:55] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[24.06 20:29:55] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
[24.06 20:29:55] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.Content$REGISTRATE.<clinit>(Content.kt:62) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:classloading}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.Content.<clinit>(Content.kt:80) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:mixin,re:classloading}
[24.06 20:29:55] [Server] 	at com.possible_triangle.sliceanddice.SliceAndDice.<init>(SliceAndDice.java:16) ~[sliceanddice-forge-2.1.0-forge.jar%23878!/:2.1.{re:classloading}
[24.06 20:29:55] [Server] 	... more
```

**Comment by PssbleTrngle** [comment]
You are not using the latest version of the mod
