### ISSUE TITLE
Fertilizer Texture missing, Forge 47.1.0, MC 1.20.1, SliceAndDice 3.0.0

### ISSUE THREAD

**Issue by LastAi** [PssbleTrngle/SliceAndDice#86]
### What happened?

Photo and Relevant Log included
![image](https://github.com/PssbleTrngle/SliceAndDice/assets/24506878/e4158ab5-a812-40f9-bdc3-b8ad283f30a3)

Also: Your Issue field "Minecraft Version" doesn't include 1.20 yet.
Love the mod by the way.

### Loader

forge

### Mod Version

3.0,0

### Minecraft Version

1.20

### Relevant log output

```shell
[16:51:22] [Worker-Main-2/ERROR] [minecraft/ModelManager]: Failed to load model sliceanddice:models/item/fertilizer_bucket.json
com.google.gson.JsonParseException: Model loader 'forge:bucket' not found. Registered loaders: supplementaries:rope_knot, supplementaries:jar, supplementaries:faucet, forge:empty, computercraft:turtle, supplementaries:blackboard, supplementaries:mimic_block, supplementaries:goblet, functionalstorage:framedblock, forge:elements, forge:obj, forge:fluid_container, forge:composite, athena:athena, forge:separate_transforms, forge:item_layers, supplementaries:flower_box, supplementaries:frame_block, supplementaries:wall_lantern, moonlight:lazy_copy, supplementaries:hanging_pot
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserializeGeometry(ExtendedBlockModelDeserializer.java:97) ~[forge-1.20.1-47.1.0-universal.jar%23261!/:?] {re:classloading}
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserialize(ExtendedBlockModelDeserializer.java:55) ~[forge-1.20.1-47.1.0-universal.jar%23261!/:?] {re:classloading}
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserialize(ExtendedBlockModelDeserializer.java:38) ~[forge-1.20.1-47.1.0-universal.jar%23261!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23100!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23256!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23256!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23256!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.block.model.BlockModel.m_111461_(BlockModel.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23256!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_246478_(ModelManager.java:110) ~[client-1.20.1-20230612.114412-srg.jar%23256!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

**Comment by PssbleTrngle** [comment]
Thank you very much, should be resolved in the newest version

**Comment by LastAi** [comment]
Thank you very much!
